### ISSUE TITLE
Torubles with the Pro

### ISSUE THREAD

**Issue by csimpi** [scotch-io/scotch-box-pro#18]
Hi, thank you for your vagrant boxes.
I've used the free version of scotch box for years. I purchased the pro, I'm trying to switch but I'm getting strange bugs during configuring the Pro version.

After the first vagrant up the ssh key doesn't work anymore, I don't know why.

```
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

```

After the first vagrant reboot, I'm getting this, I can't get into the box anymore. I don't change anything regarding the ssh things at all. I've tried to destroy the machine and start again, I'm getting this all the time. This is not happening with the free version on the same PC in the same time, I think this is some kind of bug in PRO version.

**Comment by whatnickcodes** [comment]
https://box.scotch.io/common-questions/

Search "Weird Authentication Issues"

**Comment by whatnickcodes** [comment]
Also, just try uninstalling and reinstalling. It's weird and annoying but works

**Comment by csimpi** [comment]
Thank you, but that's not an explanation only a hacky solution to avoid and not solve the real problem. 

I'm after the reinstalling, I did it many times, I'm still getting this...

I just noticed, If I make a completely raw install, I'm getting this:

```
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

So what is the real fix? I'm not comfortable with hacky solutions, my codes and my entire work into the vagrant machine, so I'd need to be sure about my stuffs won't disappear or something like that...
